name: Build and deploy ASP.Net Core app via FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Update appsettings.json
        run: |
          $appsettings = "src/its.gamify.api/appsettings.json"
          (Get-Content $appsettings) -replace '"DefaultConnection":\s*""', '"DefaultConnection": "${{ secrets.CON_STRING }}"' | Set-Content $appsettings
          (Get-Content $appsettings) -replace '"S3AccessKey":\s*""', '"S3AccessKey": "${{ secrets.S3_ACCESS_KEY }}"' | Set-Content $appsettings
          (Get-Content $appsettings) -replace '"S3SecretKey":\s*""', '"S3SecretKey": "${{ secrets.S3_SECRET_KEY }}"' | Set-Content $appsettings
          (Get-Content $appsettings) -replace '"S3BucketName":\s*""', '"S3BucketName": "${{ secrets.S3_BUCKET_NAME }}"' | Set-Content $appsettings
          (Get-Content $appsettings) -replace '"S3BaseObjectUrl":\s*""', '"S3BaseObjectUrl": "${{ secrets.S3_BASE_OBJECT_URL }}"' | Set-Content $appsettings
          (Get-Content $appsettings) -replace '"ServiceAccountAdmin":\s*""', '"ServiceAccountAdmin": "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ADMIN }}"' | Set-Content $appsettings
          (Get-Content $appsettings) -replace '"ServiceAccountPass":\s*""', '"ServiceAccountPass": "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PASS }}"' | Set-Content $appsettings
          (Get-Content $appsettings) -replace '"ApiKey":\s*""', '"ApiKey": "${{ secrets.FIREBASE_API_KEY }}"' | Set-Content $appsettings
        shell: pwsh

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "v9.0"

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{ github.workspace }}/publish"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish

      - name: Deploy to SFTP Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: site32340.siteasp.net
          username: site32340
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: sftp # Thay đổi sang sftp để sử dụng SSH
          port: 22 # Port cho SFTP từ OCR
          local-dir: ./publish/
          server-dir: /wwwroot/
          dangerous-clean-slate: false # Giữ nguyên, chỉ thay nếu cần xóa sạch (xem bên dưới)
          timeout: 120000
          log-level: verbose # Thêm để debug chi tiết hơn
